# Generated by Django 3.2 on 2021-04-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shorts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=10000)),
            ],
        ),
    ]
