# Generated by Django 3.2 on 2021-04-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shorts', '0003_auto_20210426_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='url',
            field=models.TextField(max_length=10000, unique=True),
        ),
    ]
